set(VAMP_FOUND NOTFOUND)

FIND_PATH(VAMP_INCLUDE_DIR NAMES vamp.mod)
FIND_LIBRARY(VAMP_LIBRARY vamp)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VAMP DEFAULT_MSG VAMP_LIBRARY VAMP_INCLUDE_DIR)
IF(VAMP_FOUND)
        SET(VAMP_LIBRARIES ${VAMP_LIBRARY})
        SET(VAMP_INCLUDE_DIRS ${VAMP_INCLUDE_DIR})
ELSE(VAMP_FOUND)
        SET(VAMP_LIBRARIES NOTFOUND)
        SET(VAMP_INCLUDE_DIRS NOTFOUND)
ENDIF(VAMP_FOUND)

MARK_AS_ADVANCED(VAMP_INCLUDE_DIRS VAMP_LIBRARIES)
